In [1]:
a = [1,2,3,4]
b = a
print a , b


[1, 2, 3, 4] [1, 2, 3, 4]


In [2]:
b[0] = 100
print a
# a and b has the same index

[100, 2, 3, 4]


In [3]:
a = (10,)
print type(a)

<type 'tuple'>


In [4]:
a = (10)
print type(a)

<type 'int'>


In [6]:
type(b)

list

In [10]:
type(tuple(b))

tuple

In [11]:
%timeit [1,2,3,4,5]

10000000 loops, best of 3: 142 ns per loop


In [12]:

%timeit [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]


The slowest run took 7.19 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 278 ns per loop


In [13]:

%timeit (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25)


10000000 loops, best of 3: 23.8 ns per loop


In [20]:
from numpy.random import rand
raw = rand(10000,3)
lst = [ i for i in raw]
tpl = tuple(tuple(i) for i in raw)

In [22]:
%timeit lst

10000000 loops, best of 3: 28.7 ns per loop


In [24]:
%timeit tpl

The slowest run took 75.17 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 28.9 ns per loop


In [25]:
lst

[array([ 0.92532914,  0.72105163,  0.19294115]),
 array([ 0.80919702,  0.22590901,  0.32982359]),
 array([ 0.11427229,  0.09596924,  0.32497596]),
 array([ 0.10011731,  0.30744248,  0.34926616]),
 array([ 0.35566847,  0.42204366,  0.1927086 ]),
 array([ 0.56323307,  0.26211914,  0.81127987]),
 array([ 0.27233192,  0.44470163,  0.40535597]),
 array([ 0.93678544,  0.20865563,  0.44356718]),
 array([ 0.006215  ,  0.49438553,  0.15000161]),
 array([ 0.52794396,  0.02304111,  0.37593167]),
 array([ 0.81352237,  0.2415122 ,  0.97769688]),
 array([ 0.42836631,  0.59781824,  0.37936056]),
 array([ 0.20698135,  0.13036007,  0.0146104 ]),
 array([ 0.75279736,  0.74435434,  0.51652473]),
 array([ 0.97851452,  0.54079766,  0.0963618 ]),
 array([ 0.55793498,  0.36389473,  0.34394187]),
 array([ 0.17923915,  0.73484335,  0.23093403]),
 array([ 0.7582126 ,  0.75161572,  0.94856317]),
 array([ 0.23443768,  0.94876175,  0.46296959]),
 array([ 0.56706764,  0.20166342,  0.88383725]),
 array([ 0.60009597,

In [28]:
%timeit for data in lst: list(data)

100 loops, best of 3: 10.9 ms per loop


In [30]:
%timeit for data in lst: zi = data[0]+1

100 loops, best of 3: 2.83 ms per loop


In [29]:
%timeit for data2 in tpl: tuple(data2)

1000 loops, best of 3: 1.29 ms per loop


In [15]:
a = rand(5)
a

array([ 0.02153518,  0.49056836,  0.45608859,  0.79356273,  0.89044952])

In [17]:
for i in a:
    print i

0.0215351806852
0.490568359531
0.456088593994
0.793562729792
0.890449520213
